### ISSUE TITLE
Animation duration input not working after upgrading to Chart.js 3.9.1

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-charts#163]
**Describe the bug**
The `animationDuration` input of the chart component is not working after latest upgrade of Chart.js version (to v3.9,1). It always uses the default value of 1000ms.

**To Reproduce**
1. Create a component for a line chart with random data
2. Define the `animationDuration` input and set it to a value of 0
3. Check how the chart is displayed
4. The chart is shown with an animation while configured not to.

**Expected behavior**
The animation duration should be configured to the time defined through the `animationDuration` input.

**Additional context**
After further investigation, this bug comes from a change of the structure of the animations configuration objects in chart.js library:
- According to documentation, in previous version (2.9.4), this configuration was defined through an `animation` object with `duration` property (see https://www.chartjs.org/docs/2.9.4/configuration/animations.html). 
- In current new version (3.9.1), this object has changed to be `animations` changed (see https://www.chartjs.org/docs/3.9.1/configuration/animations.html).

**Comment by fjaguado** [comment]
Fixed in version 15.1.1
