### ISSUE TITLE
Add support for point annotations

### ISSUE THREAD

**Issue by joaquimvila** [systelab/systelab-charts#197]
Point annotations are used to mark points on the chart area. This can be useful for highlighting values that are of interest.
This feature is provided by the **chartjs-plugin-annotation** (https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/types/point.html), but should be exposed through the library interface to be used by consumers of this library.

**Comment by fjaguado** [comment]
This has been already added in version 17.2.0
