### ISSUE TITLE
Upgrade charts.js

### ISSUE THREAD

**Issue by alfonsserra** [systelab/systelab-charts#8]

**Comment by OscarDeDios** [comment]
It would be convenient to upgrade chartjs to the last version to take advantage of last features. 

In concrete in our project we would like to use the last version of chartjs-plugin-annotation that only works with chartjs 3.x. The annotation plugin now allows to draw lines with more control specifying x and y axis values, in the previous version only accept value and endValue, we need more control.

**Comment by fjaguado** [comment]
There is a path to update ChartJS to the newest version in other issues
