### ISSUE TITLE
Vertical and Horizontal Meter: secundary ruler marks numbers are not proportional

### ISSUE THREAD

**Issue by hrcnlz** [systelab/systelab-charts#82]
![A2 secundary lines numbers not exact 2](https://user-images.githubusercontent.com/62311761/115862888-fcb66a80-a434-11eb-93ef-7d3755ec5ea3.png)
![A2 secundary lines numbers not exact](https://user-images.githubusercontent.com/62311761/115862889-fd4f0100-a434-11eb-83a0-1255c9a4869c.png)

**Comment by olgapuig** [comment]
There is no plan to fix this defect so I have removed it from the Backlog.

**Comment by fjaguado** [comment]
Due the meters have been moved to its own Library I suggest to open there the issue. https://github.com/systelab/systelab-meters
